### ISSUE TITLE
huaweidload

### ISSUE THREAD

**Issue by saqie1393** [baselsayeh/e5577s_modified_source#2]
hi dear 

you can patched this file  i upload 2 file  one not  patched 2nd are patched...

Valdikss asked 

> I've patched "huaweidload" binary file found on the recovery partition of Android kernel (it's called "second" if you unpack it with android-unpackbootimg).

patching huaweidload so that you can flash any firmware, either by collecting your kernel from the source, disabling the efuse check, removing all the code from the source blocking processor, or replacing it with true, that is, everything is ok and continue working, even if the processor is locked and the signature is not valid.

1: (https://www.mediafire.com/file/1j0azgt2nqefylw/huaweidload.7z/file

2: https://www.mediafire.com/file/ldo9x6yrquy0qym/huaweidload_Patched.7z/file

**Comment by baselsayeh** [comment]
Hello
You can re-use the patched huawei dload across firmware versions using the same device.

The files that you have provided me seems to be from different firmware versions/devices, which firmware version the patched huaweidload binary is based from??
________________________________
From: saqie1393 ***@***.***>
Sent: Saturday, May 22, 2021 9:25 AM
To: baselsayeh/e5577s_modified_source ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [baselsayeh/e5577s_modified_source] huaweidload (#2)


hi dear

you can patched this file i upload 2 file one not patched 2nd are patched...

Valdikss asked

I've patched "huaweidload" binary file found on the recovery partition of Android kernel (it's called "second" if you unpack it with android-unpackbootimg).

patching huaweidload so that you can flash any firmware, either by collecting your kernel from the source, disabling the efuse check, removing all the code from the source blocking processor, or replacing it with true, that is, everything is ok and continue working, even if the processor is locked and the signature is not valid.

<https://www.mediafire.com/file/1j0azgt2nqefylw/huaweidload.7z/file>

https://www.mediafire.com/file/ldo9x6yrquy0qym/huaweidload_Patched.7z/file

**Comment by saqie1393** [comment]
Both are V7R22  Base

1  E5785
2  B525 Patched

**Comment by baselsayeh** [comment]
> Both are V7R22 Base
> 
> 1 E5785
> 2 B525 Patched

Provide me with full details. Which firmware versions?
And can you provide me of an unmodified huaweidload binary of the same firmware version?

**Comment by saqie1393** [comment]
https://www.mediafire.com/file/dn9flo8kyewdrlh/huaweidload_M_Patched_E8372_21.328.03.00.00.7z/file

https://www.mediafire.com/file/0tkilfqdvtq8dyi/huaweidload_original_E8372_21.328.03.00.00.7z/file

V7R11 E8372 

Check this ....

**Comment by baselsayeh** [comment]
Here is the modified file
[huaweidload.zip](https://github.com/baselsayeh/e5577s_modified_source/files/6533905/huaweidload.zip)

**Comment by saqie1393** [comment]
> Here is the modified file
> [huaweidload.zip](https://github.com/baselsayeh/e5577s_modified_source/files/6533905/huaweidload.zip)
> 

which version ? what changes in huaweidload? Datalock disabled?

**Comment by saqie1393** [comment]
M - firmware with a patched so-called firmware server that allows you to flash unsigned firmware and web interfaces

**Comment by baselsayeh** [comment]
> M - firmware with a patched so-called firmware server that allows you to flash unsigned firmware and web interfaces

The patches are the same as E8372, which should allow you to skip signature checks.
But be careful, it seems that the device "E5785" will not accept firmware flashing without the modified "adb firmware".
You can try this patched usbdload, but this may not work. Try it and recover the modem via the the boot pin

**Comment by saqie1393** [comment]
How to disable signature verfication ...ida pro do this fuction? for other modem..?
